### ISSUE TITLE
This is faulty

### ISSUE THREAD

**Issue by dsetzer** [snapo/Python-Bustabit-and-Bustadice-Simulator#1]
This isn't producting the correct values. When I generate 10 million results with it they have a median of 1.97. I don't know where the flaw is at and don't have time to fix it for you but this should be having a median of 1.98.

**Comment by snapo** [comment]
Yes you are right... im checking why this behavior is :-(

**Comment by snapo** [comment]
seems now a very strange behavior... if i use math.ceil (to take the upper bound) the values are correct, if i use math.floor the values (as you pointed out) are wrong... But the original code uses math.floor .... will check the javascript code again maybe i overlooked something.

**Comment by dsetzer** [comment]
This is very strange I agree, I have been doing more testing, it is the same way even in javascript I am getting 1.97, so it's not just your code, and even asking shiba for the median of the last 100,000 games she's also giving me 1.97 and I've asked her two different days. I've contacted Daniel about it but received no reply yet,  it's gotta be mandela effect..
